In [1]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow import keras


In [2]:
tf.__version__

'2.16.1'

In [4]:
A = tf.constant([[5, 3],
                [6, 1]])
A

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 3],
       [6, 1]])>

In [5]:
hello = tf.constant('Hello world')
hello

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello world'>

In [7]:
hello.numpy().decode('utf-8')

'Hello world'

In [10]:
a = tf.constant(2021)
b = tf.constant(303)
c = a+b
c.numpy()

2324